# .gitlab-ci.yml
stages:
  - build
  - test
  - report

variables:
  MAVEN_CLI_OPTS: "-B -s .m2/settings.xml --batch-mode"
  JAVA_HOME: "/usr/lib/jvm/java-21-openjdk"
  PATH: "$JAVA_HOME/bin:$PATH"

# Job to build the project
build:
  stage: build
  image: maven:3.9.2-openjdk-21
  script:
    - echo "Building the project..."
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/
    expire_in: 1 week

# Job to run Karate tests
karate-tests:
  stage: test
  image: maven:3.9.2-openjdk-21
  script:
    - echo "Running Karate tests..."
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    paths:
      - target/karate-reports/
    expire_in: 1 week
  allow_failure: false

# Job to generate the detailed Cucumber report
generate-report:
  stage: report
  image: maven:3.9.2-openjdk-21
  script:
    - echo "Generating Cucumber report..."
    - mvn $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="execution.scenarios.KarateTestSuite"
  artifacts:
    paths:
      - target/karate-reports/
    expire_in: 1 week

# Schedule the pipeline
# Note: This cron schedule must be set in GitLab CI/CD > Schedules
# Schedule example: everyday at 08:00
# Cron: 0 8 * * *
